[package]
name = "rift"
version = "0.1.0"
edition = "2024"

[dependencies]
deno_ast = { version = "0.53.0", features = ["transpiling", "visit"] }
deno_lint = "0.83.0"
deno_core = "0.385.0"
anyhow = "1.0.102"
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
clap = "4.5.60"
