use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let mut config: cbindgen::Config = Default::default();
    config.language = cbindgen::Language::C;
    config.autogen_warning = Some("/* Autogenerated file, do not edit */".to_string());
    config.cpp_compat = true;
    config.braces = cbindgen::Braces::SameLine;
    config.line_length = 80;
    config.tab_width = 4;
    config.documentation_style = cbindgen::DocumentationStyle::C;
    config.style = cbindgen::Style::Tag;

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("include/rift/engine.h");
}
