[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-embed = { version = "8.5.0", features = [
    "include-exclude",
    "debug-embed",
    "interpolate-folder-path",
] }
