[project]
name = "02_single_project"
version = "0.1.0"
authors = [""]
description = ""
url = ""
plugins = "rift/plugins.ts"
metadata = "rift/metadata.ts"
dependencies = "rift/dependencies.ts"

[target]
name = "02_single_target"
type = "bin"

# [task.build] # Command name
# about = "Compile local packages and all of their dependencies."
# after_help = "Run `<cyan,bold>cargo help build</>` for more detailed information.\n"
# args = [
#     { name = "release", short = "r", conflict_with = 'profile', help = "Build artifacts in release mode, with optimizations", help_heading = "Complication Options" },
# ]
# is_command = true
