[project]
name = "02_single_project"
version = "0.1.0"
authors = [""]
description = ""
url = ""
plugins = "rift/plugins.ts"
metadata = "rift/metadata.ts"


[target]
name = "02_single_target"
type = "bin"
