[project]
name = "example-cpp"
version = "0.1.0"
authors = ["Rift Dev Team"]
dependencies = "rift/dependencies.ts"
plugins = "rift/plugins.ts"
metadata = "rift/metadata.ts"

[target]
name = "example-cpp"
type = "bin"
build = "rift/build.ts"
