[build] # Command name

about = "Compile local packages and all of their dependencies."
after_help = "Run `<cyan,bold>cargo help build</>` for more detailed information.\n"
flags = [
    { name = "release", short = "r", conflict_with = "profile", help = "Build artifacts in release mode, with optimizations", help_heading = "Complication Options" },
]

[generate]
about = "Generate code from Rift.toml to other build system, such as Visual Studio, XCode, etc."
after_help = "Run `<cyan,bold>rift help generate</>` for more detailed information.\n"
flags = [
    { name = "vs", short = "r", conflict_with = "xcode", help = "Build artifacts in release mode, with optimizations", help_heading = "Complication Options" },
]
