[package]
name = "rift"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["string"] }
once_cell = "1.20.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

[build-dependencies]
